### ISSUE TITLE
Reverse-engineering issue for Avro schema with multiple items with union types

### ISSUE THREAD

**Issue by marchanc** [hackolade/Avro#1]
Hi, I wrote an Avro schema which we've been using. The Avro schema has been validated against Apache 1.8.2 and has been working within XMLSpy. I tried to reverse-engineer the schema in Hackolade using the Avro plug-in but noticed that it drops all field using "union" except for the last one in the schema.
You can try the 3 versions of the same schema in the attached zip file and will see that only the last field with union is kept.

Thanks,
Claude Marchand

[person.zip](https://github.com/hackolade/Avro/files/2860799/person.zip)

**Comment by pdesmarets** [comment]
Hello Claude, I took a look at your files.  It seems to me that we're handling it, but in a way that is not intuitively obvious.  When a union involves a complex type, the we represent it in Hackolade with a oneOf choice, following JSON Schema logic.  However of all the data types of the union involve only primitive (scalar) data types, then we treat them as a <multiple> data type.  I realize that we should enhance the documentation to make this more obvious.  Can you confirm that that works for you?
![image](https://user-images.githubusercontent.com/10139210/52726958-84320480-2fb4-11e9-873a-871b2ab4f99f.png)

**Comment by marchanc** [comment]
Hi Pascal,
This is correct union types are loaded and handled fine. The issue is that only one field of type union gets reversed-engineered no matter how many are in the schema.
For the 3 examples, here is what I get. It happens to be the last field of type union, all the fields of type union prior to the last one are ignored.
Please see the screenshot from reverse-engineering all 3 examples.

[cid:image001.png@01D4C390.971527C0]

Thanks,
Claude

**Comment by pdesmarets** [comment]
Hi Claude,  I could not see the embedded picture.  Can we continue the conversion on our support lien at support@hackolade.com  ?  Thx,   Pascal

**Comment by marchanc** [comment]
![sc](https://user-images.githubusercontent.com/47602087/52791297-a1a7b280-3036-11e9-8678-1cd90f944a55.JPG)
Here is the file.
