### ISSUE TITLE
Reverse engineering Avro schema from file blanks Hackolade

### ISSUE THREAD

**Issue by olavkrause** [hackolade/Avro#134]
Hackolade version: 6.10.20
Avro plugin version: 0.1.128

Actions leading to the issue:
- Create new Hackolade model with target Apache Avro Schema
- Tools > Reverse-Engineer > Avro schema or data file > File System...
- Select .avsc file and click OK (option "Combine schema" or "Separate schema" lead to same issue)
- Processing dialog displays and processing seems to happen (CPU fan spins up)

When processing (presumably) finishes, Hackolade blanks to white canvas, menu bar still showing but all options greyed out. 

If more than one instant of Hackolade running at the time, the following error message is displayed in the console after a minute or so:

Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:86358)
    at _.send (node:electron/js2c/browser_init:2:71969)
    at sendCompressed (/home/olav/Downloads/Hackolade-linux-x64/resources/app/main.js:86:71055)
    at /home/olav/Downloads/Hackolade-linux-x64/resources/app/main.js:86:52977
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by pdesmarets** [comment]
Hello Olav,

For support it is best to submit a ticket to support@hackolade.com

Can you please provide the .avsc file which most likely includes something that the system is not expecting.  Also, can you please provide the log file Hackolade.log	captured immediately after a failure from your folder:
Windows:  	C:\Users\%username%\AppData\Roaming\HackoladeLogs
Mac:		Documents\HackoladeLogs 
Linux: 		/home/$[user]/Documents/HackoladeLogs

This will help our engineers troubleshoot.  Best regards
