### ISSUE TITLE
Avro annotations support

### ISSUE THREAD

**Issue by samuelramos** [hackolade/Avro#166]
To my understanding the current Avro plugin version doesn't support the definiton annotations at entity or field level. 

I wanted to start this thread to discuss the usage of "[Configure custom properties](https://hackolade.com/help/Configurecustomproperties.html)" at entity or field level, to feed annotation "Tags" on the generated avro schema.

**AVSC Sample:**

```
{
  "type" : "record",
  "name" : "Customer",
  "fields" : [ {
    "name" : "CustomerFullName",
    "type" : {
      "type" : "string",
      "tags" : [ "PII","Sensitive" ]
    }
  }
],
 "tags" : [ "PII","Sensitive" ]
}
```

**IDL sample:**

```
 @tags(["PII", "Sensitive"])
  record Customer {
     @tags(["PII", "Sensitive"])
      string CustomerFullName;
  }
```

**Comment by pdesmarets** [comment]
We have a flag that you can set in custom properties includeInScript which will allow you to see your custom prop, like tags, show up in the Avro schema output.

```
			{
				"propertyName": "Tags",
				"propertyKeyword": "tags",
				"propertyTooltip": "Select from list of options",
				"propertyType": "multipleCheckboxSelect",
				"options": [
					"PII",
					"GDPR",
					"Sensitive",
					"Protected"
				],
				"includeInScript": true
			},
```
We'll update the documentation https://github.com/hackolade/plugins to include this information.

**Comment by pdesmarets** [comment]
documentation https://github.com/hackolade/plugins updated, plus annotations capability added at https://hackolade.com/help/Avroschema.html#Annotations
